[package]
edition = "2021"
name = "cql-stress"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runnable_macro = { path = "runnable_macro" }
anyhow = "1.0.52"
async-trait = "0.1.52"
base64 = "0.13.0"
chrono = "0.4.9"
env_logger = "0.9.0"
futures = "0.3.19"
hdrhistogram = "7.5.0"
openssl = "0.10.32"
parking_lot = "0.12.0"
rand = "0.8"
rand_distr = "0.4"
rand_pcg = "0.3"
scylla = {version = "0.5.0", features = ["ssl"]}
sha2 = "0.10"
thread_local = "1.1.4"
tokio = {version = "1.15.0", features = ["full"]}# TODO: Include only necessary features
tracing = {version = "0.1.35", features = ["log"]}

[dev-dependencies]
ntest = "0.8"
